services:
    # Servicio para la base de datos MongoDB
    db-fashionline:
        image: sebastian190030/db-fashionline:latest
        container_name: fashionline-db
        ports:
            - "27018:27017"
        volumes:
            - mongo_data:/data/db
        networks:
            - fashionline-network

    # Servicio para la API
    api-fashionline:
        image: sebastian190030/api-fashionline:latest
        container_name: fashionline-api
        environment:
            - APP_NAME=fashionline-API
            - PORT=8091
            - TITLE=fashionline API
            - DESCRIPTION=Documentación de la API REST de fashionline
            - VERSION=1.0.0
            - AUTHOR=Fashionline Developers
            - DATA_CONNECTION_METHOD=mongodb
            - DATA_SOURCE_USERNAME=admin
            - DATA_SOURCE_PASSWORD=admin
            - DATA_SOURCE_DOMAIN=db-fashionline:27017
            - DATA_SOURCE_DB=fashionline
            - DATA_PARAMS=authSource=admin&directConnection=true&serverSelectionTimeoutMS=100000&socketTimeoutMS=10000&appName=mongo
            - SECURITY_JWT_SECRET_KEY=c8e9b6803afbcfa6edd9569c94c75ff4b144622b0a0570a636dffd62c24a3476
            - SECURITY_JWT_EXPIRATION=86400000
            - SECURITY_PUBLIC_ROUTES=/auth/login,/auth/verify
            - HEADER_CORS_ALLOWED_ORIGINS=http://localhost:5173
            - DEBUGGER_MODE=INFO
        ports:
            - "8091:8091"
        depends_on:
            - db-fashionline
        networks:
            - fashionline-network

    web-fashionline:
        image: sebastian190030/web-fashionline:latest
        container_name: fashionline-web
        environment:
            - VITE_API_BASE_URL=http://localhost:8091
        ports:
            - "5173:5173"
        networks:
            - fashionline-network

# Volúmenes para persistencia de datos
volumes:
    mongo_data:

# Red de contenedores para comunicación entre servicios
networks:
    fashionline-network:
        driver: bridge
